### ISSUE TITLE
Add yourself to the Contributors.md file, be part of the fun!

### ISSUE THREAD

**Issue by RaidAndFade** [RaidAndFade/HacktoberChallenges2018#258]
Add yourself to the contributors.md file, easy to do!

Add yourself in the middle of other people, and follow the format so that the merge can be quick and easy.

[Link to Contributors.md](https://github.com/RaidAndFade/Hacktoberfest2018/blob/master/contributors.md)

Also, be part of the fun! Complete issues #1 and #227 (and the rest that will  come out as the event goes on)

**Comment by fineanmol** [comment]
Just Check this Repo Also of Hacktober Fest to win T-shirt ..        [Repo Hacktoberfest2k18](https://github.com/fineanmol/Hacktoberfest2k18)
